{
    'name': 'CRM Base',
    'version': '1.0',
    'category': 'CRM',
    'author': 'Đỗ Duy Chiến',
    'sequence': '10',
    'summary': 'Custom workflow CRM',
    'depends': [
        'crm',
        'custom_partner',
        'sale',
        'sale_management',
        'sale_crm',
        'account',
        'stock',
        'sh_message',
        'sci_brand'
    ],
    'data': [
        'security/crm_base_sc.xml',
        'static/templates/assets.xml',
        'security/ir.model.access.csv',
        'data/data_no_update.xml',
        'data/default_data.xml',
        'data/cron_update_stage_voucher.xml',
        'wizard/view_booking_guarantee.xml',
        'wizard/apply_discount_view.xml',
        'views/case.xml',
        'views/history_discount.xml',
        'views/view_brand.xml',
        'views/view_partner.xml',
        'views/inherit_view_all.xml',
        'views/crm_program_discount_view.xml',
        'views/crm_voucher_program_view.xml',
        'views/crm_voucher.xml',
        'views/view_crm_type.xml',
        'views/view_crm_line.xml',
        'views/view_phone_call.xml',
        'views/view_lead.xml',
        'views/view_booking.xml',
        'views/view_discount_review_mng.xml',
        'views/debt_review.xml',
        'wizard/view_assign.xml',
        'wizard/check_partner_view_form.xml',
        'wizard/view_select_service.xml',
        'wizard/share_booking_view.xml',
        'wizard/cancel_booking_view.xml',
        'wizard/discount_review.xml',
        'views/sync.xml',
        'views/request_deposit.xml',
        'views/view_sale_order.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
